name: "CartPlugin"
version: "${project.version}"
main: "com.motschik.spigotplugin.CartPlugin"
api-version: "1.16"

commands:
  sp:
    description: change gamemode to spectator.
  su:
    description: change gamemode to survival.
  message:
    description: messages.