
name: マスターブランチへのプッシュ時にビルド・タグ更新

on:
  push:
    branches:
      - 'master'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Javaセットアップ JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: バージョンアップ
      run: mvn versions:set -DremoveSnapshot
    - name: Mavenビルド
      run: mvn -B package --file pom.xml
    - name: ビルド成果物のアップロード
      run: |
        mkdir staging
        cp target/*.jar staging
    - uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: staging

  version-up:
    runs-on: ubuntu-latest
    environment:
      name: prod
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Javaセットアップ JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: SNAPSHOTを外す
      run: mvn versions:set -DremoveSnapshot
    - run: |
        git config --local user.email "motschik@users.noreply.github.com"
        git config --local user.name "motschik"
        git add pom.xml
        git commit -m "Remove snapshot."
        git push
    - name: タグ付け
      id: create_tag
      run: |
        VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`
        git tag ${VERSION}
        git push origin ${VERSION}
        echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
    - name: ビルド成果物のダウンロード
      uses: actions/download-artifact@v4
      with:
        name: artifact
    - name: バージョンアップ
      run: mvn versions:set -DnextSnapshot
    - run: |
        git add pom.xml
        git commit -m "Set next version with SNAPSHOT."
        git push
    - name: Create Release
      run: gh release create ${{steps.create_tag.outputs.version}} *.jar --generate-notes
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}